### ISSUE TITLE
NameError: name 'Bool' is not defined. Did you mean: 'bool'?

### ISSUE THREAD

**Issue by R10943169** [Gy-Hu/pybmc#1]
Traceback (most recent call last):
  File "pybmc/main.py", line 44, in <module>
    bmc = bmc.BMC(*m.parse(file))
  File "pybmc/model.py", line 302, in parse
    inp[it] = Bool(name)

Hi, I found this problem while trying to execute your program, I would like to ask if there is any class missing in your code.

**Comment by Gy-Hu** [comment]
Hi, have you tried to execute inside the project folder rather than execute `python pybmc/main.py` outside the project folder? In addition, you also need to install z3 in your Python environment cuz `Bool` actually is `z3.Bool` (but I have used `from z3 import *` so the `z3.` just been ignored), its not commonly boolean type.

**Comment by R10943169** [comment]
Thank you for your reply. Here is the command I use
->python main.py --aag dataset/aig_benchmark/hwmcc07_amba/spec10-and-env.aag --k 1
the version of z3 is '0.2.0', and I also tried to modify your code as follows but still not working
    6    import z3
303            inp[it] = z3.Bool(name)

Error messages:
------------------
Traceback (most recent call last):
  File "pybmc/main.py", line 44, in <module>
    bmc = bmc.BMC(*m.parse(file))
  File "pybmc/model.py", line 303, in parse
    inp[it] = z3.Bool(name)
AttributeError: module 'z3' has no attribute 'Bool'

**Comment by Gy-Hu** [comment]
I got you. You installed the wrong package. Actually, in python you shouldn't install z3 as `pip install z3` . You should use `pip install z3-solver` instead. This is so weird but I have got used to it lol. The version I used is `z3-solver                  4.8.17.0` (checked in `pip list` ) . You can try to execute some really small demo of z3py, it you didn't encounter problem of that but still cant execute this repo, please let me know.

**Comment by Gy-Hu** [comment]
The problem seems to have been solved, if you have further question just open a new one :)
